name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches-ignore:
      - releases

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: '20'
          cache: 'npm'
      - run: corepack enable && corepack enable npm
      - run: npm ci
      - run: npm run all
      - run: tar -czf action.tar.gz dist scripts action.yml
      - uses: actions/upload-artifact@v7
        with: 
          if-no-files-found: error
          path: action.tar.gz
          archive: false

  test: # make sure the action works on a clean machine without building
    needs: [build]
    strategy:
      fail-fast: false
      matrix: 
        on:
          - ubuntu-latest
        unity:
          - 2022.3.22f1
          - 6000.0.59f2
    runs-on: ${{ matrix.on }}
    steps:
      - uses: actions/download-artifact@v8
        with:
          name: action.tar.gz
      - run: mkdir -p action && tar xzf action.tar.gz -C action && rm action.tar.gz

      - name: Prepare project
        env:
          UNITY_VERSION: ${{ matrix.unity }}
        run: |-
          mkdir -p Assets ProjectSettings Packages
          echo "m_EditorVersion: $UNITY_VERSION" > ProjectSettings/ProjectVersion.txt
          cat <<EOF > Packages/manifest.json
          {
              "com.unity.test-framework": "1.1.33",
              "com.unity.testtools.codecoverage": "1.2.7"
          }
          EOF

      - uses: ./action
        with:
          licenseXml: ${{ secrets.UNITY_LICENSE_XML }}
      - uses: actions/upload-artifact@v7
        with:
          name: artifact-${{ matrix.unity }}
          path: artifacts

  conclude:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs:
      - build
      - test
    steps:
      - name: Conclude Tests
        env: { NEEDS: "${{ toJSON(needs) }}" }
        run: |
          echo "$NEEDS" | jq -c '. | to_entries[] | [.key, .value.result]'
          echo "$NEEDS" | jq -e '. | all(.result == "success")' > /dev/null
